export const chmViewerStyle = `
.chm-viewer{position:relative;width:100%;height:100%;min-height:480px;display:flex;flex-direction:column;overflow:hidden;background:#edf2f6;color:#182233;font:14px/1.45 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;box-sizing:border-box}
.chm-viewer *{box-sizing:border-box}
.chm-header{min-height:62px;display:flex;align-items:center;gap:12px;padding:10px 16px;border-bottom:1px solid rgba(24,34,51,.1);background:rgba(255,255,255,.94)}
.chm-sidebar-toggle{display:none;width:36px;height:36px;border:0;border-radius:10px;background:#e8f3ee;color:#08785c;font:inherit;font-size:19px;cursor:pointer}
.chm-heading{min-width:0;flex:1}.chm-heading h2{margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:17px;line-height:1.35}.chm-heading p{margin:2px 0 0;color:#667085;font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.chm-badges{display:flex;align-items:center;gap:7px;flex-wrap:wrap;justify-content:flex-end}.chm-badge{padding:4px 8px;border-radius:999px;background:#e8f3ee;color:#08785c;font-size:11px;font-weight:750}.chm-badge.is-muted{background:#eef1f4;color:#596579}
.chm-body{flex:1;min-height:0;display:grid;grid-template-columns:minmax(230px,300px) minmax(0,1fr)}
.chm-sidebar{min-height:0;display:flex;flex-direction:column;border-right:1px solid rgba(24,34,51,.1);background:#f8fafb}
.chm-tabs{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:4px;padding:8px;border-bottom:1px solid rgba(24,34,51,.08)}
.chm-tab{height:34px;border:0;border-radius:8px;background:transparent;color:#647084;font:inherit;font-size:12px;font-weight:750;cursor:pointer}.chm-tab:hover{background:#eef3f5}.chm-tab.is-active{background:#fff;color:#08785c;box-shadow:0 1px 5px rgba(24,34,51,.12)}
.chm-sidebar-panels{flex:1;min-height:0;position:relative}.chm-panel{position:absolute;inset:0;overflow:auto;padding:8px}.chm-panel[hidden]{display:none}
.chm-navigation,.chm-navigation ul{margin:0;padding:0;list-style:none}.chm-navigation ul{padding-left:14px;border-left:1px solid rgba(24,34,51,.09)}
.chm-nav-button,.chm-search-result{width:100%;display:block;border:0;border-radius:8px;background:transparent;color:inherit;font:inherit;text-align:left;cursor:pointer}.chm-nav-button{min-height:32px;padding:6px 8px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.chm-nav-button:hover,.chm-nav-button.is-active{background:#e7f3ee;color:#08785c}.chm-nav-label{min-height:28px;padding:5px 8px;color:#526073;font-weight:650}
.chm-panel-note{margin:10px;padding:9px 10px;border-radius:8px;background:#fff6df;color:#845a00;font-size:12px}
.chm-search-box{position:sticky;top:-8px;z-index:1;padding:8px 2px;background:#f8fafb}.chm-search-box input{width:100%;height:36px;padding:0 11px;border:1px solid rgba(24,34,51,.16);border-radius:9px;background:#fff;color:inherit;font:inherit;outline:none}.chm-search-box input:focus{border-color:#0a8b68;box-shadow:0 0 0 3px rgba(10,139,104,.12)}
.chm-search-meta{margin:7px 4px;color:#6b7688;font-size:11px}.chm-search-results{display:flex;flex-direction:column;gap:5px}.chm-search-result{padding:9px;background:#fff;border:1px solid rgba(24,34,51,.08)}.chm-search-result:hover{border-color:rgba(10,139,104,.35);box-shadow:0 5px 16px rgba(24,34,51,.07)}.chm-search-result strong,.chm-search-result span{display:block}.chm-search-result strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.chm-search-result span{margin-top:3px;color:#677386;font-size:11px;line-height:1.4}.chm-search-result mark{background:#fff1a6;color:inherit}
.chm-topic{min-width:0;min-height:0;display:flex;flex-direction:column;background:#dfe5ea}.chm-topic-bar{min-height:42px;display:flex;align-items:center;gap:8px;padding:7px 12px;background:rgba(255,255,255,.88);border-bottom:1px solid rgba(24,34,51,.08)}.chm-topic-bar strong{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.chm-topic-path{margin-left:auto;max-width:48%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#6b7688;font-size:11px}
.chm-topic-frame{display:block;flex:1;min-height:0;width:100%;border:0;background:#fff}
.chm-state{position:absolute;inset:62px 0 0;z-index:6;display:flex;align-items:center;justify-content:center;gap:12px;background:rgba(237,242,246,.88);backdrop-filter:blur(2px)}.chm-state[hidden]{display:none}.chm-spinner{width:32px;height:32px;border:3px solid rgba(8,120,92,.16);border-top-color:#08785c;border-radius:999px;animation:chm-spin .85s linear infinite}.chm-state p{margin:0;color:#435168;font-weight:650}
.chm-error{position:absolute;inset:82px 18px auto;z-index:8;width:min(560px,calc(100% - 36px));margin:auto;padding:16px;border:1px solid rgba(190,91,0,.22);border-radius:14px;background:#fff8e9;color:#743f00;box-shadow:0 18px 48px rgba(24,34,51,.18)}.chm-error[hidden]{display:none}.chm-error strong{display:block;font-size:15px}.chm-error p{margin:6px 0 0;white-space:pre-wrap;overflow-wrap:anywhere}
@keyframes chm-spin{to{transform:rotate(360deg)}}
[data-viewer-theme=dark] .chm-viewer{background:#111827;color:#e6edf6}[data-viewer-theme=dark] .chm-header,[data-viewer-theme=dark] .chm-topic-bar{background:#151d2b;border-color:rgba(148,163,184,.18)}[data-viewer-theme=dark] .chm-heading p,[data-viewer-theme=dark] .chm-topic-path{color:#94a3b8}[data-viewer-theme=dark] .chm-sidebar,[data-viewer-theme=dark] .chm-search-box{background:#121a27;border-color:rgba(148,163,184,.18)}[data-viewer-theme=dark] .chm-tab.is-active,[data-viewer-theme=dark] .chm-search-result,[data-viewer-theme=dark] .chm-search-box input{background:#1c2635;color:#e6edf6}[data-viewer-theme=dark] .chm-topic{background:#0b1019}[data-viewer-theme=dark] .chm-state{background:rgba(17,24,39,.88);color:#dbe5f1}
@media(prefers-color-scheme:dark){[data-viewer-theme=system] .chm-viewer{background:#111827;color:#e6edf6}[data-viewer-theme=system] .chm-header,[data-viewer-theme=system] .chm-topic-bar{background:#151d2b;border-color:rgba(148,163,184,.18)}[data-viewer-theme=system] .chm-heading p,[data-viewer-theme=system] .chm-topic-path{color:#94a3b8}[data-viewer-theme=system] .chm-sidebar,[data-viewer-theme=system] .chm-search-box{background:#121a27;border-color:rgba(148,163,184,.18)}[data-viewer-theme=system] .chm-tab.is-active,[data-viewer-theme=system] .chm-search-result,[data-viewer-theme=system] .chm-search-box input{background:#1c2635;color:#e6edf6}[data-viewer-theme=system] .chm-topic{background:#0b1019}[data-viewer-theme=system] .chm-state{background:rgba(17,24,39,.88);color:#dbe5f1}}
@media(max-width:760px){.chm-sidebar-toggle{display:inline-flex;align-items:center;justify-content:center}.chm-body{grid-template-columns:1fr}.chm-sidebar{position:absolute;z-index:5;top:62px;bottom:0;left:0;width:min(88vw,310px);box-shadow:16px 0 36px rgba(24,34,51,.18);transform:translateX(-105%);transition:transform .2s ease}.chm-viewer.is-sidebar-open .chm-sidebar{transform:translateX(0)}.chm-badges .chm-badge.is-muted{display:none}.chm-topic-path{display:none}}
`;
