import assert from 'node:assert/strict'
import { build } from 'esbuild'
import { readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const require = createRequire(import.meta.url)
const output = resolve(root, 'src/maplibre-worker-source.ts')
const upstreamLicense = await readFile(require.resolve('maplibre-gl/package.json').replace(/package\.json$/, 'LICENSE.txt'), 'utf8')
const result = await build({
  entryPoints: [require.resolve('maplibre-gl/dist/maplibre-gl-worker.mjs')],
  bundle: true,
  write: false,
  metafile: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  minify: true,
  legalComments: 'inline',
})
assert.equal(result.outputFiles.length, 1)
for (const entry of Object.values(result.metafile.outputs)) {
  assert.equal(entry.imports.length, 0, 'MapLibre worker must not fetch external modules')
}
const code = '// Generated by scripts/build-worker.mjs; keeps the lazy map runtime self-contained.\n' +
  `export const maplibreWorkerSource: string = ${JSON.stringify(`/*!\n${upstreamLicense}\n*/\n${result.outputFiles[0].text}`)};\n`
let previous
try { previous = await readFile(output, 'utf8') } catch (error) {
  if (error.code !== 'ENOENT') throw error
}
if (previous !== code) await writeFile(output, code)
console.log(`[renderer-geo] Bundled ${result.outputFiles[0].contents.length} worker bytes without external imports.`)
