// Generated OOXML fixtures. Values and drawing coordinates are test data only.
const namespaces = 'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"';
const relation = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const cache = (kind, count, points) => `<c:${kind}><c:ptCount val="${count}"/>${points.map(([i,v]) => `<c:pt idx="${i}"><c:v>${v}</c:v></c:pt>`).join('')}</c:${kind}>`;
const paragraph = text => `<w:p><w:r><w:t>${text}</w:t></w:r></w:p>`;
function chart(type, categories, values, count) {
  return `<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart"><c:chart><c:plotArea><c:${type}><c:ser><c:idx val="0"/><c:order val="0"/><c:tx><c:v>Test series</c:v></c:tx><c:cat><c:strRef>${cache('strCache',count,categories)}</c:strRef></c:cat><c:val><c:numRef>${cache('numCache',count,values)}</c:numRef></c:val></c:ser></c:${type}></c:plotArea></c:chart></c:chartSpace>`;
}
const inlineChart = (i) => `<w:p><w:r><w:drawing><wp:inline><wp:extent cx="5486400" cy="3086100"/><wp:docPr id="${i}" name="Chart ${i}"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/chart"><c:chart r:id="chart${i}"/></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>`;
export async function makeEngineDocument(JSZip) {
  const zip=new JSZip();
  const cats = Array.from({length:16},(_,i)=>[i*2,`${i*2+1}日`]);
  const values=Array.from({length:32},(_,i)=>[i,i+1]);
  const charts=[chart('lineChart',cats,values,32),chart('lineChart',[[0,'A'],[1,'B'],[2,'C']],[[2,2],[0,1]],3),chart('barChart',[[0,'A'],[1,'B'],[2,'C']],[[0,-2],[2,3]],3),chart('pieChart',[[2,'Only']],[[2,1]],3)];
  zip.file('[Content_Types].xml',`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>${charts.map((_,i)=>`<Override PartName="/word/chart${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.drawingml.chart+xml"/>`).join('')}</Types>`);
  zip.file('_rels/.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="document" Type="${relation}/officeDocument" Target="word/document.xml"/></Relationships>`);
  zip.file('word/_rels/document.xml.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${charts.map((_,i)=>`<Relationship Id="chart${i+1}" Type="${relation}/chart" Target="chart${i+1}.xml"/>`).join('')}<Relationship Id="picture" Type="${relation}/image" Target="media/picture.png"/></Relationships>`);
  charts.forEach((xml,i)=>zip.file(`word/chart${i+1}.xml`,xml));
  zip.file('word/media/picture.png',Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jP1kAAAAASUVORK5CYII=','base64'));
  const drawing = `<w:p><w:r><w:drawing><wp:anchor distT="0" distB="0" distL="0" distR="0" simplePos="0" relativeHeight="1" behindDoc="0" locked="0" layoutInCell="1" allowOverlap="1"><wp:simplePos x="0" y="0"/><wp:positionH relativeFrom="column"><wp:posOffset>914400</wp:posOffset></wp:positionH><wp:positionV relativeFrom="paragraph"><wp:posOffset>127000</wp:posOffset></wp:positionV><wp:extent cx="457200" cy="457200"/><wp:wrapSquare wrapText="right"/><wp:docPr id="20" name="Floating test square"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="1" name="Square"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="picture"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="457200" cy="457200"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:anchor></w:drawing></w:r></w:p>`;
  zip.file('word/document.xml',`<w:document ${namespaces}><w:body>${paragraph('Generated compatibility document')}${charts.map((_,i)=>inlineChart(i+1)).join('')}${drawing}${paragraph('Text after the floating square')}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720"/></w:sectPr></w:body></w:document>`);
  return zip.generateAsync({type:'uint8array',compression:'DEFLATE'});
}
