/** Japanese product-demo copy shared by desktop, mobile, dialogs and accessibility labels. */
export const demoCopyJa = {
  pageTitle: 'File Viewer Demo — Office・PDF・CADをブラウザで表示',
  pureWeb: 'Pure Web',
  local: 'ローカル',
  link: 'リンク',
  pasteLink: 'リンクを貼り付け',
  upload: 'アップロード',
  samples: 'サンプル',
  search: '検索',
  more: 'その他',
  home: 'ホーム',
  previewWorkspace: 'プレビュー画面に戻る',
  openFile: 'ファイルを開く',
  openFromLink: 'リンクから開く',
  openFromDevice: 'デバイスからアップロード',
  browseSamples: 'サンプルを見る',
  settings: '設定',
  fullSettings: '詳細設定',
  settingsTitle: 'プレビュー設定',
  settingsDescription: '現在のファイルの表示方法を調整します',
  settingsDisplayTab: '表示',
  settingsToolbarTab: 'ツールバーと検索',
  settingsFormatsTab: '形式別設定',
  closeSettings: 'プレビュー設定を閉じる',
  displaySettings: '表示とレイアウト',
  themeMode: 'テーマモード',
  systemTheme: 'システムに合わせる',
  lightTheme: 'ライト',
  darkTheme: 'ダーク',
  styleIsolation: 'スタイル分離',
  density: '表示密度',
  comfortable: '標準',
  compact: 'コンパクト',
  surfaceBackground: 'ページ外の背景',
  surfaceTransparent: '透過表示',
  surfaceDefault: '形式の既定値',
  fitPadding: 'ページ余白',
  fitResize: '自動フィット',
  fitUntilInteraction: '操作するまで維持',
  fitAlways: '常に維持',
  fitInitial: '初回のみ',
  fitScaleRange: '倍率範囲',
  watermarkSettings: '透かし',
  watermarkText: '透かし文字',
  watermarkOpacity: '不透明度',
  watermarkRotation: '回転角度',
  watermarkSpacing: '横 / 縦の間隔',
  watermarkFontSize: '文字サイズ',
  watermarkColor: '色',
  externalToolbarSettings: '外部ツールバー',
  externalToolbarHint: '元の Demo 機能をすべて維持し、公開 API からプレビューアーを操作します。',
  searchSettings: '検索動作',
  enableSearch: '文書検索を有効化',
  caseSensitive: '大文字と小文字を区別',
  wholeWord: '単語単位で一致',
  maxMatches: '最大一致件数',
  showSearch: '検索',
  showZoom: 'ズーム',
  showDownload: 'ダウンロード',
  showPrint: '印刷',
  showExportHtml: 'HTML 書き出し',
  formatSettings: '現在の形式',
  formatSelector: '設定する形式',
  currentFormat: '現在のファイル',
  pdfFormat: 'PDF',
  wordFormat: 'Word',
  sheetFormat: 'スプレッドシート',
  textFormat: 'テキスト / コード',
  archiveFormat: '圧縮ファイル',
  cadFormat: 'CAD',
  geoFormat: '地理空間データ',
  modelFormat: '3D モデル / STEP',
  modelSettingsHint: '以下の OCCT 解析設定は STEP、IGES、BREP に適用されます。',
  drawingFormat: '図表',
  visualPagination: '疑似ページ分割',
  progressiveRendering: '段階的レンダリング',
  strictWordCompatibility: 'Word 互換性を厳密にする',
  awaitLayout: 'レイアウトの安定を待つ',
  hideWebHiddenContent: 'Web 非表示内容を隠す',
  ignoreLastPageBreak: '前回の改ページを無視',
  pdfToolbar: 'PDF 内蔵ツールバー',
  pdfNavigation: 'ナビゲーションパネル',
  defaultNavigationVisible: '既定でナビゲーションを開く',
  pdfThumbnails: 'ページサムネイル',
  pdfRotation: '初期回転',
  pdfStreaming: 'ストリーミング',
  cjkFontFallback: 'CJK フォントフォールバック',
  identityFontRepair: 'Identity フォント修復',
  resizableColumns: '列幅のドラッグ変更',
  resizableRows: '行高のドラッグ変更',
  textEncoding: 'テキストエンコーディング',
  workerThreshold: 'Worker しきい値',
  textToolbar: 'ソース情報バー',
  lineNumbers: '行番号を表示',
  virtualizeThreshold: '仮想レンダリングしきい値',
  markdownVirtualizeThreshold: 'Markdown ソースしきい値（0 はレイアウトを維持）',
  maxRenderedLine: '1 行のレンダリング上限',
  overscanLines: '先読み行数',
  archiveCache: '展開結果をキャッシュ',
  archiveEntryDownload: '内部ファイルのダウンロードを許可',
  maxArchiveSize: '圧縮ファイルの最大サイズ',
  maxEntryPreview: '内部プレビュー上限',
  cadRenderer: 'レンダラー',
  cadFitMode: '初期フィット',
  cadFitPadding: '図面の表示比率',
  includePaperSpace: 'ペーパースペースを含める',
  lineWeightMode: '線幅モード',
  bestFit: 'スマート境界',
  nativeBounds: '元の境界',
  geoBasemap: 'ベースマップ',
  inferProjection: '座標系を自動推定',
  preferMapEngine: '地図エンジンを優先',
  geoFitPadding: '境界余白',
  modelUseWorker: 'Worker で解析',
  modelWorkerTimeout: '解析タイムアウト',
  modelLinearUnit: '長さの単位',
  modelUnitMillimeter: 'ミリメートル (mm)',
  modelUnitCentimeter: 'センチメートル (cm)',
  modelUnitMeter: 'メートル (m)',
  modelUnitInch: 'インチ (in)',
  modelUnitFoot: 'フィート (ft)',
  modelDeflectionType: '線形偏差モード',
  modelDeflectionRatio: 'バウンディングボックス比率',
  modelDeflectionAbsolute: '絶対値',
  modelLinearDeflection: '線形偏差',
  modelAngularDeflection: '角度偏差（rad）',
  preferOfficialDrawing: '公式図表ランタイムを優先',
  reloadHint: '適用後、安全にプレビューを更新し、現在位置を復元します。',
  noFormatSettings: 'この形式には推奨の既定値が適用されています。',
  resetDefaults: '既定値に戻す',
  cancel: 'キャンセル',
  applySettings: '設定を適用',
  settingsApplied: '設定を適用しました',
  settingsApplyFailed: '設定を適用できませんでした。値を確認して再試行してください。',
  integration: '組み込み',
  toggleSourcePanel: 'ファイルパネルを切り替え',
  quickSamples: 'クイックサンプル',
  quickSamplesHint: 'よく使う形式をすぐに開く',
  sampleFile: 'サンプルファイル',
  collapse: '折りたたむ',
  open: '開く',
  address: 'アドレス',
  addressPlaceholder: 'ファイルの URL を入力',
  linkPanelTitle: 'リンクから開く',
  linkPanelHint: '相対パス、サブディレクトリ、完全な URL に対応',
  uploadPanelTitle: 'デバイスからアップロード',
  uploadPanelHint: 'ファイルはこのブラウザー内だけで処理され、サーバーには送信されません',
  samplesPanelTitle: 'サンプルライブラリ',
  preview: 'プレビュー',
  closePanel: '操作パネルを閉じる',
  chooseFile: 'クリックしてファイルを選択',
  openLocal: 'このデバイスから開く',
  recentOpened: '最近開いたファイル',
  closeRecent: '最近開いたファイルを閉じる',
  showRecent: '最近開いたファイルを表示',
  openRecent: '開く',
  dismissRecent: '最近開いたファイルから削除',
  reselectLocalFile: 'ブラウザーはローカルファイルを保持しません。「{name}」をもう一度選択してください。',
  unselected: 'ファイルが選択されていません',
  documentInfo: '文書情報',
  closeDocumentInfo: '文書情報を閉じる',
  fileSource: '入力元',
  filePath: 'パス',
  fileFormat: '形式',
  previewActions: 'プレビュー操作',
  zoomControls: 'ズーム操作',
  zoomOut: '縮小',
  zoomIn: '拡大',
  resetZoom: '倍率をリセット',
  fitMode: 'フィット',
  fitDefault: '既定',
  fitAuto: '自動',
  fitContain: '全体を表示',
  fitCover: '領域を埋める',
  fitWidth: '幅',
  fitHeight: '高さ',
  fitActual: '100%',
  fitScaleDown: '縮小のみ',
  download: 'ダウンロード',
  downloadTitle: '元のファイルをダウンロード',
  print: '印刷',
  printTitle: 'レンダリング済みの全内容を印刷',
  printDirect: '直接印刷',
  printMask: 'マスクして印刷',
  printMaskTitle: '機密領域を隠してから印刷',
  exportHtml: 'HTML',
  exportHtmlTitle: '現在のレンダリング結果を HTML として書き出す',
  watermark: '透かし',
  watermarkTitle: '透かしを切り替え',
  searchDocument: '文書検索',
  searchPlaceholder: '現在の文書を検索',
  previousResult: '前の検索結果',
  nextResult: '次の検索結果',
  closeSearch: '検索を閉じる',
  closeMobileControls: 'モバイル操作パネルを閉じる',
  openLinkSettings: 'リンク設定を開く',
  openSamples: 'サンプルファイルを開く',
  uploadLocalFile: 'ローカルファイルをアップロード',
  searchCurrentDocument: '現在の文書を検索',
  openMoreActions: 'その他の操作を開く',
  reset: 'リセット',
  auto: 'AUTO',
  language: '言語',
  theme: 'テーマ',
  themeToLight: 'ライトモードに切り替え',
  themeToDark: 'ダークモードに切り替え',
  integrationSnippet: '組み込みコード',
  openIntegrationSnippet: '組み込みコードを表示',
  integrationSnippetHint: '例を開いてコピーできます',
  integrationSnippetDescription: 'React の完全な組み込み例',
  closeIntegrationSnippet: '組み込みコードを閉じる',
  copySnippet: 'コードをコピー',
  copiedSnippet: 'コピーしました',
} as const
