/** German product-demo copy shared by desktop, mobile, dialogs, and accessibility labels. */
export const demoCopyDe = {
  pageTitle: "Datei-Viewer-Demo – Office, PDF und CAD in Ihrem Browser",
  pureWeb: "Reines Web",
  local: "Lokal",
  link: "URL",
  pasteLink: "Link einfügen",
  upload: "Hochladen",
  samples: "Proben",
  search: "Suchen",
  more: "Mehr",
  home: "Heim",
  previewWorkspace: "Kehren Sie zum Vorschau-Arbeitsbereich zurück",
  openFile: "Datei öffnen",
  openFromLink: "Geöffnet von URL",
  openFromDevice: "Vom Gerät hochladen",
  browseSamples: "Durchsuchen Sie Beispiele",
  settings: "Einstellungen",
  fullSettings: "Vollständige Einstellungen",
  settingsTitle: "Vorschaueinstellungen",
  settingsDescription: "Optimieren Sie die Darstellung der aktuellen Datei",
  settingsDisplayTab: "Anzeige",
  settingsToolbarTab: "Symbolleiste und Suche",
  settingsFormatsTab: "Formatoptionen",
  closeSettings: "Schließen Sie die Vorschaueinstellungen",
  displaySettings: "Anzeige und Layout",
  themeMode: "Themenmodus",
  systemTheme: "System",
  lightTheme: "Licht",
  darkTheme: "Dunkel",
  styleIsolation: "Stilisolation",
  density: "Grenzflächendichte",
  comfortable: "Komfortabel",
  compact: "Kompakt",
  surfaceBackground: "Hintergrund der Außenseite",
  surfaceTransparent: "Immersiv",
  surfaceDefault: "Formatvorgabe",
  fitPadding: "Seitenauffüllung",
  fitResize: "Reaktionsfreudige Passform",
  fitUntilInteraction: "Bis zur Interaktion",
  fitAlways: "Stets",
  fitInitial: "Nur anfänglich",
  fitScaleRange: "Skalenbereich",
  watermarkSettings: "Wasserzeichen",
  watermarkText: "Wasserzeichentext",
  watermarkOpacity: "Opazität",
  watermarkRotation: "Drehung",
  watermarkSpacing: "Horizontaler/vertikaler Spalt",
  watermarkFontSize: "Schriftgröße",
  watermarkColor: "Farbe",
  externalToolbarSettings: "Externe Symbolleiste",
  externalToolbarHint: "Behält alle Original-Demo-Aktionen bei und führt den Zuschauer durch seine öffentlichen API.",
  searchSettings: "Suchverhalten",
  enableSearch: "Dokumentensuche aktivieren",
  caseSensitive: "Groß- und Kleinschreibung beachten",
  wholeWord: "Ganzes Wort",
  maxMatches: "Maximale Übereinstimmungen",
  showSearch: "Suchen",
  showZoom: "Zoom",
  showDownload: "Herunterladen",
  showPrint: "Drucken",
  showExportHtml: "HTML-Export",
  formatSettings: "Aktuelles Format",
  formatSelector: "Format konfigurieren",
  currentFormat: "Aktuelle Datei",
  pdfFormat: "PDF",
  wordFormat: "Wort",
  sheetFormat: "Kalkulationstabelle",
  textFormat: "Text/Code",
  archiveFormat: "Archiv",
  cadFormat: "CAD",
  geoFormat: "Geodaten",
  modelFormat: "3D-Modell / STEP",
  modelSettingsHint: "Diese OCCT-Parsing-Steuerelemente gelten für STEP, IGES und BREP.",
  drawingFormat: "Zeichnung",
  visualPagination: "Visuelle Paginierung",
  progressiveRendering: "Progressives Rendering",
  strictWordCompatibility: "Strenge Word-Kompatibilität",
  awaitLayout: "Warten Sie auf ein stabiles Layout",
  hideWebHiddenContent: "Verstecken Sie im Internet verborgene Inhalte",
  ignoreLastPageBreak: "Zuletzt gerenderte Seitenumbrüche ignorieren",
  pdfToolbar: "Integrierte PDF-Symbolleiste",
  pdfNavigation: "Navigationsbereich",
  defaultNavigationVisible: "Navigation standardmäßig öffnen",
  pdfThumbnails: "Miniaturansichten der Seiten",
  pdfRotation: "Erste Rotation",
  pdfStreaming: "Streaming",
  cjkFontFallback: "CJK-Font-Fallback",
  identityFontRepair: "Reparatur von Identitätsschriftarten",
  resizableColumns: "In der Größe veränderbare Spalten",
  resizableRows: "Größenveränderbare Zeilen",
  textEncoding: "Textkodierung",
  workerThreshold: "Arbeiterschwelle",
  textToolbar: "Quellmetadatenleiste",
  lineNumbers: "Zeilennummern anzeigen",
  virtualizeThreshold: "Virtualisierungsschwellenwert",
  markdownVirtualizeThreshold: "Markdown-Quellenschwellenwert (0 bleibt gerendert)",
  maxRenderedLine: "Begrenzung der gerenderten Linie",
  overscanLines: "Overscan-Linien",
  archiveCache: "Extrahierte Einträge im Cache speichern",
  archiveEntryDownload: "Downloads von Einträgen zulassen",
  maxArchiveSize: "Maximale Archivgröße",
  maxEntryPreview: "Limit für die Eintragsvorschau",
  cadRenderer: "Renderer",
  cadFitMode: "Erste Passform",
  cadFitPadding: "Verhältnis des Zeichnungsansichtsfensters",
  includePaperSpace: "Berücksichtigen Sie den Papierbereich",
  lineWeightMode: "Linienstärkenmodus",
  bestFit: "Intelligente Grenzen",
  nativeBounds: "Einheimische Grenzen",
  geoBasemap: "Grundkarte",
  inferProjection: "Projektion ableiten",
  preferMapEngine: "Bevorzugen Sie die Karten-Engine",
  geoFitPadding: "Randpolsterung",
  modelUseWorker: "Analysieren Sie einen Worker",
  modelWorkerTimeout: "Parse-Timeout",
  modelLinearUnit: "Lineareinheit",
  modelUnitMillimeter: "Millimeter (mm)",
  modelUnitCentimeter: "Zentimeter (cm)",
  modelUnitMeter: "Meter (m)",
  modelUnitInch: "Zoll (in)",
  modelUnitFoot: "Fuß (ft)",
  modelDeflectionType: "Linearer Ablenkungsmodus",
  modelDeflectionRatio: "Begrenzungsrahmenverhältnis",
  modelDeflectionAbsolute: "Absoluter Wert",
  modelLinearDeflection: "Lineare Ablenkung",
  modelAngularDeflection: "Winkelablenkung (rad)",
  preferOfficialDrawing: "Bevorzugen Sie die offizielle Zeichenlaufzeit",
  reloadHint: "Durch die sichere Anwendung wird die Vorschau aktualisiert und Ihre Position wiederhergestellt.",
  noFormatSettings: "Dieses Format verwendet die empfohlenen Standardeinstellungen.",
  resetDefaults: "Standardeinstellungen zurücksetzen",
  cancel: "Stornieren",
  applySettings: "Einstellungen übernehmen",
  settingsApplied: "Einstellungen angewendet",
  settingsApplyFailed: "Einstellungen konnten nicht angewendet werden. Überprüfen Sie die Werte und versuchen Sie es erneut.",
  integration: "Integrieren",
  toggleSourcePanel: "Dateifenster umschalten",
  quickSamples: "Schnelle Proben",
  quickSamplesHint: "Öffnen Sie gängige Formate",
  sampleFile: "Beispieldatei",
  collapse: "Zusammenbruch",
  open: "Offen",
  address: "URL",
  addressPlaceholder: "Fügen Sie eine Datei URL ein",
  linkPanelTitle: "Geöffnet von URL",
  linkPanelHint: "Unterstützt relative Pfade, Unterverzeichnisse und vollständige URLs",
  uploadPanelTitle: "Vom Gerät hochladen",
  uploadPanelHint: "Dateien bleiben in diesem Browser und werden nie auf einen Server hochgeladen",
  samplesPanelTitle: "Beispielbibliothek",
  preview: "Vorschau",
  closePanel: "Bedienfeld schließen",
  chooseFile: "Wählen Sie eine Datei",
  openLocal: "Von diesem Gerät aus öffnen",
  recentOpened: "Kürzlich eröffnet",
  closeRecent: "Schließen Sie kürzlich geöffnet",
  showRecent: "Die Show wurde kürzlich eröffnet",
  openRecent: "Offen",
  dismissRecent: "Aus zuletzt geöffneter Datei entfernen",
  reselectLocalFile: "Browser behalten keine lokalen Dateien. Wählen Sie erneut „{name}“.",
  unselected: "Keine Datei ausgewählt",
  documentInfo: "Dokumentinformationen",
  closeDocumentInfo: "Dokumentinformationen schließen",
  fileSource: "Quelle",
  filePath: "Weg",
  fileFormat: "Format",
  previewActions: "Vorschau der Aktionen",
  zoomControls: "Zoom-Steuerelemente",
  zoomOut: "Herauszoomen",
  zoomIn: "Vergrößern",
  resetZoom: "Zoom zurücksetzen",
  fitMode: "Fit",
  fitDefault: "Standard",
  fitAuto: "Auto",
  fitContain: "Enthalten",
  fitCover: "Abdeckung",
  fitWidth: "Breite",
  fitHeight: "Höhe",
  fitActual: "100 %",
  fitScaleDown: "Verkleinern",
  download: "Herunterladen",
  downloadTitle: "Laden Sie die Originaldatei herunter",
  print: "Drucken",
  printTitle: "Drucken Sie vollständig gerenderte Inhalte",
  printDirect: "Jetzt drucken",
  printMask: "Maskieren und drucken",
  printMaskTitle: "Decken Sie empfindliche Bereiche vor dem Drucken ab",
  exportHtml: "HTML",
  exportHtmlTitle: "Gerendertes HTML exportieren",
  watermark: "Wasserzeichen",
  watermarkTitle: "Wasserzeichen umschalten",
  searchDocument: "Dokumentensuche",
  searchPlaceholder: "Durchsuchen Sie dieses Dokument",
  previousResult: "Vorheriges Suchergebnis",
  nextResult: "Nächstes Suchergebnis",
  closeSearch: "Suche schließen",
  closeMobileControls: "Schließen Sie die mobilen Steuerelemente",
  openLinkSettings: "Öffnen Sie die URL-Einstellungen",
  openSamples: "Beispieldateien öffnen",
  uploadLocalFile: "Laden Sie eine lokale Datei hoch",
  searchCurrentDocument: "Durchsuchen Sie dieses Dokument",
  openMoreActions: "Weitere Aktionen öffnen",
  reset: "Zurücksetzen",
  auto: "AUTO",
  language: "Sprache",
  theme: "Thema",
  themeToLight: "Wechseln Sie in den Lichtmodus",
  themeToDark: "Wechseln Sie in den Dunkelmodus",
  integrationSnippet: "Integrationscode",
  openIntegrationSnippet: "Integrationscode anzeigen",
  integrationSnippetHint: "Öffnen und kopieren Sie ein fokussiertes Beispiel",
  integrationSnippetDescription: "Vollständiges React-Integrationsbeispiel",
  closeIntegrationSnippet: "Schließen Sie den Integrationscode",
  copySnippet: "Code kopieren",
  copiedSnippet: "Kopiert",
}

export default demoCopyDe
